import commonjs from "@rollup/plugin-commonjs";
import json from '@rollup/plugin-json';
import nodeResolve from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";
import typescript from "@rollup/plugin-typescript";
import fs from "node:fs";
import path from "node:path";
import url from "node:url";
import { createRequire } from "node:module";

const isWatching = !!process.env.ROLLUP_WATCH;
const require = createRequire(import.meta.url);
const sdPlugin = "de.boriskemper.sonos-controller.sdPlugin";

/**
 * @type {import('rollup').RollupOptions}
 */
const config = {
	input: "src/plugin.ts",
	output: {
		file: `${sdPlugin}/bin/plugin.js`,
		sourcemap: isWatching,
		sourcemapPathTransform: (relativeSourcePath, sourcemapPath) => {
			return url.pathToFileURL(path.resolve(path.dirname(sourcemapPath), relativeSourcePath)).href;
		}
	},
	plugins: [
		{
			name: "watch-externals",
			buildStart: function () {
				this.addWatchFile(`${sdPlugin}/manifest.json`);
			},
		},
		typescript({
			mapRoot: isWatching ? "./" : undefined
		}),
		nodeResolve({
			browser: false,
			exportConditions: ["node"],
			preferBuiltins: true,
			// One Stream Deck SDK: the kit (a peer of it) must use the plugin's copy, also when it
			// is linked from a local checkout that has its own
			dedupe: ["@elgato/streamdeck", "@elgato/utils"]
		}),
		commonjs(),
		!isWatching && terser(),
		{
			name: "emit-module-package-file",
			generateBundle() {
				this.emitFile({ fileName: "package.json", source: `{ "type": "module" }`, type: "asset" });
			}
		},
		json()
	]
};

/**
 * Property inspector bundle (browser, loaded by ui/*.html that use the kit's PI components).
 * @type {import('rollup').RollupOptions}
 */
const propertyInspector = {
	input: "src/pi-ui/index.ts",
	output: {
		file: `${sdPlugin}/ui/pi.js`,
		format: "iife",
		sourcemap: isWatching,
	},
	plugins: [
		{
			// One JSON file per language serves the manifest, the plugin runtime and the property
			// inspectors: bundle the "Localization" blocks into a script the PI pages can load.
			name: "generate-pi-locales",
			buildStart: function () {
				const locales = {};
				for (const file of fs.readdirSync(sdPlugin)) {
					const m = /^([a-z]{2}(?:_[A-Z]{2})?)\.json$/.exec(file);
					if (!m) continue;
					this.addWatchFile(path.join(sdPlugin, file));
					locales[m[1].split("_")[0]] = JSON.parse(fs.readFileSync(path.join(sdPlugin, file), "utf8")).Localization ?? {};
				}
				fs.writeFileSync(
					`${sdPlugin}/ui/locales.generated.js`,
					`// Generated by rollup.config.mjs from the <lang>.json files. Do not edit.
window.PI_LOCALES = ${JSON.stringify(locales)};
`,
				);
			},
		},
		{
			// The shared PI theme lives in the kit; ship a copy next to the PI pages.
			name: "copy-pi-theme",
			buildStart: function () {
				const theme = require.resolve("@rocklobster42195/streamdeck-kit/styles/pi-theme.css");
				this.addWatchFile(theme);
				fs.copyFileSync(theme, `${sdPlugin}/ui/pi-theme.css`);
			},
		},
		typescript({ mapRoot: isWatching ? "./" : undefined }),
		nodeResolve({ browser: true }),
		!isWatching && terser(),
	],
};

export default [config, propertyInspector];
